comenzaremos importando las librerias necesarias

In [3]:
import pandas as pd
import numpy as np

realizamos la ingesta de archivos

In [4]:
amazon= pd.read_csv ('Datasets/amazon_prime_titles.csv')
disneyplus = pd.read_csv ('Datasets/disney_plus_titles.csv')
hulu = pd.read_csv ('Datasets/hulu_titles.csv')
netflix = pd.read_csv ('Datasets/netflix_titles.csv')

comenzamos con el proceso de EDA(Explory Data Analysis)

In [6]:
amazon.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [7]:
disneyplus. head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

In [28]:
hulu.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...

In [29]:
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Buscamos lo valores nulos y los sumamos

In [30]:
amazon.isna().sum()

show_id            0
type               0
title              0
director        2082
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [31]:
disneyplus.isna().sum()

show_id           0
type              0
title             0
director        473
cast            190
country         219
date_added        3
release_year      0
rating            3
duration          0
listed_in         0
description       0
dtype: int64

In [32]:
hulu.isna().sum()

show_id            0
type               0
title              0
director        3070
cast            3073
country         1453
date_added        28
release_year       0
rating           520
duration         479
listed_in          0
description        4
dtype: int64

In [33]:
netflix.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

vemos la cantidad de filas y columnas de cada uno

In [34]:
amazon.shape

(9668, 12)

In [35]:
disneyplus.shape

(1450, 12)

In [37]:
hulu.shape

(3073, 12)

In [38]:
netflix.shape

(8807, 12)

se identifican los datos duplicados y en caso de existir se eliminan

In [40]:
amazon[amazon.duplicated(keep=False)]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [44]:
disneyplus[disneyplus.duplicated(keep=False)]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [45]:
hulu[hulu.duplicated(keep=False)]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [46]:
netflix[netflix.duplicated(keep=False)]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

como nos  podemos dar cuenta ningun archivo tiene datos duplicados

separamos minutos y por otro lado la cantidad de temporadas

In [52]:
amazon['min']= amazon['duration'].apply(lambda i: i.split()[0] 
    if i.split()[1]=='min' 
    else '0')

amazon['seasons']= amazon['duration'].apply(lambda i: i.split()[0] 
    if i.split(" ",1)[1]=='Seasons' or i.split(" ",1)[1]=='Season' 
    else '0')

In [53]:
amazon.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...,113,0
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,110,0
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,74,0
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",69,0
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,45,0

In [54]:
disneyplus['min']= disneyplus['duration'].apply(lambda i: i.split()[0] 
    if i.split()[1]=='min' 
    else '0')

disneyplus['seasons']= disneyplus['duration'].apply(lambda i: i.split()[0] 
    if i.split(" ",1)[1]=='Seasons' or i.split(" ",1)[1]=='Season' 
    else '0')

In [55]:
disneyplus.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!,23,0
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...,91,0
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.,23,0
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!",41,0
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...,0,1

In [57]:
hulu['min']= amazon['duration'].apply(lambda i: i.split()[0] 
    if i.split()[1]=='min' 
    else '0')

hulu['seasons']= amazon['duration'].apply(lambda i: i.split()[0] 
    if i.split(" ",1)[1]=='Seasons' or i.split(" ",1)[1]=='Season' 
    else '0')

In [58]:
hulu.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...,113,0
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r...",110,0
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...,74,0
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...,69,0
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...,45,0

In [59]:
netflix['min']= amazon['duration'].apply(lambda i: i.split()[0] 
    if i.split()[1]=='min' 
    else '0')

netflix['seasons']= amazon['duration'].apply(lambda i: i.split()[0] 
    if i.split(" ",1)[1]=='Seasons' or i.split(" ",1)[1]=='Season' 
    else '0')

In [60]:
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",113,0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",110,0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,74,0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",69,0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,45,0

In [71]:

#amazon
#creaar ID
amazon['ID']= ['a'] + amazon['show_id']
#remplazar los valores los nulos en raiting por G:
amazon['rating'] = amazon ['rating'].replace(np.nan, 'g')
#formato de fechas 
amazon['date_added'] = pd.to_datetime(amazon['date_added'], format= '%B %d, %Y')
#Modificar los campos de texto para que esten en minusculas
amazon['type'] = amazon['type'].str.lower()
amazon['title'] = amazon['title'].str.lower()
amazon['director'] = amazon['director'].str.lower()
amazon['cast'] = amazon['cast'].str.lower()
amazon['country'] = amazon['country'].str.lower()
amazon['rating'] = amazon['rating'].str.lower()
amazon['duration'] = amazon['duration'].str.lower()
amazon['listed_in'] = amazon['listed_in'].str.lower()
amazon['description'] = amazon['description'].str.lower()

In [72]:
amazon

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons,ID
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,113,0,as1
1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,110,0,as2
2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,74,0,as3
3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",69,0,as4
4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,45,0,as5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,movie,pride of the bowery,joseph h. lewis,"leo gorcey, bobby jordan",NaN,NaT,1940,7+,60 min,comedy,new york city street principles get an east si...,60,0,as9664
9664,s9665,tv show,planet patrol,NaN,"dick vosburgh, ronnie stevens, libby morris, m...",NaN,NaT,2018,13+,4 seasons,tv shows,"this is earth, 2100ad - and these are the adve...",0,4,as9665
9665,s9666,movie,outpost,steve barker,"ray stevenson, julian wadham, richard brake, m...",NaN,NaT,2008,r,90 min,action,"in war-torn eastern europe, a world-weary grou...",90,0,as9666
9666,s9667,tv show,maradona: blessed dream,NaN,"esteban recagno, ezequiel stremiz, luciano vit...",NaN,NaT,2021,tv-ma,1 season,"drama, sports","the series tells the story of diego maradona, ...",0,1,as9667
9667,s9668,movie,harry brown,daniel barber,"michael caine, emily mortimer, joseph gilgun, ...",NaN,NaT,2010,r,103 min,"action, drama, suspense","harry brown, starring two-time academy award w...",103,0,as9668

In [91]:
#disneyplus
#creaar ID
disneyplus['ID']= ['a'] + disneyplus['show_id']
#remplazar los valores los nulos en raiting por G:
disneyplus['rating'] = disneyplus ['rating'].replace(np.nan, 'g')
#formato de fechas 
disneyplus['date_added'] = pd.to_datetime(disneyplus['date_added'], format= '%B %d, %Y')
#Modificar los campos de texto para que esten en minusculas
disneyplus['type'] = disneyplus['type'].str.lower()
disneyplus['title'] = disneyplus['title'].str.lower()
disneyplus['director'] = disneyplus['director'].str.lower()
disneyplus['cast'] = disneyplus['cast'].str.lower()
disneyplus['country'] = disneyplus['country'].str.lower()
disneyplus['rating'] = disneyplus['rating'].str.lower()
disneyplus['duration'] = disneyplus['duration'].str.lower()
disneyplus['listed_in'] = disneyplus['listed_in'].str.lower()
disneyplus['description'] = disneyplus['description'].str.lower()

In [95]:
disneyplus

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons,ID,duration_int,duration_type
0,s1,movie,duck the halls: a mickey mouse christmas special,"alonso ramirez ramos, dave wasson","chris diamantopoulos, tony anselmo, tress macn...",NaN,2021-11-26,2016,tv-g,23 min,"animation, family",join mickey and the gang as they duck the halls!,23,0,as1,23,min
1,s2,movie,ernest saves christmas,john cherry,"jim varney, noelle parker, douglas seale",NaN,2021-11-26,1988,pg,91 min,comedy,santa claus passes his magic bag to a new st. ...,91,0,as2,91,min
2,s3,movie,ice age: a mammoth christmas,karen disher,"raymond albert romano, john leguizamo, denis l...",united states,2021-11-26,2011,tv-g,23 min,"animation, comedy, family",sid the sloth is on santa's naughty list.,23,0,as3,23,min
3,s4,movie,the queen family singalong,hamish hamilton,"darren criss, adam lambert, derek hough, alexa...",NaN,2021-11-26,2021,tv-pg,41 min,musical,"this is real life, not just fantasy!",41,0,as4,41,min
4,s5,tv show,the beatles: get back,NaN,"john lennon, paul mccartney, george harrison, ...",NaN,2021-11-25,2021,g,1 season,"docuseries, historical, music",a three-part documentary from peter jackson ca...,0,1,as5,1,season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445,s1446,movie,x-men origins: wolverine,gavin hood,"hugh jackman, liev schreiber, danny huston, wi...","united states, united kingdom",2021-06-04,2009,pg-13,108 min,"action-adventure, family, science fiction",wolverine unites with legendary x-men to fight...,108,0,as1446,108,min
1446,s1447,movie,night at the museum: battle of the smithsonian,shawn levy,"ben stiller, amy adams, owen wilson, hank azar...","united states, canada",2021-04-02,2009,pg,106 min,"action-adventure, comedy, family",larry daley returns to rescue some old friends...,106,0,as1447,106,min
1447,s1448,movie,eddie the eagle,dexter fletcher,"tom costello, jo hartley, keith allen, dickon ...","united kingdom, germany, united states",2020-12-18,2016,pg-13,107 min,"biographical, comedy, drama","true story of eddie edwards, a british ski-jum...",107,0,as1448,107,min
1448,s1449,movie,bend it like beckham,gurinder chadha,"parminder nagra, keira knightley, jonathan rhy...","united kingdom, germany, united states",2020-09-18,2003,pg-13,112 min,"buddy, comedy, coming of age",despite the wishes of their traditional famili...,112,0,as1449,112,min
1449,s1450,movie,captain sparky vs. the flying saucers,mark waring,charlie tahan,united states,2020-04-01,2012,tv-g,2 min,"action-adventure, animals & nature, animation",view one of sparky's favorite home movies.,2,0,as1450,2,min

In [76]:
#hulu
#creaar ID
hulu['ID']= ['a'] + hulu['show_id']
#remplazar los valores los nulos en raiting por G:
hulu['rating'] = hulu ['rating'].replace(np.nan, 'g')
#formato de fechas 
hulu['date_added'] = pd.to_datetime(hulu['date_added'], format= '%B %d, %Y')
#Modificar los campos de texto para que esten en minusculas
hulu['type'] = hulu['type'].str.lower()
hulu['title'] = hulu['title'].str.lower()
hulu['director'] = hulu['director'].str.lower()
hulu['country'] = hulu['country'].str.lower()
hulu['rating'] = hulu['rating'].str.lower()
hulu['duration'] = hulu['duration'].str.lower()
hulu['listed_in'] = hulu['listed_in'].str.lower()
hulu['description'] = hulu['description'].str.lower()

In [77]:
hulu

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons,ID
0,s1,movie,ricky velez: here's everything,NaN,NaN,NaN,2021-10-24,2021,tv-ma,NaN,"comedy, stand up",​comedian ricky velez bares it all with his ho...,113,0,as1
1,s2,movie,silent night,NaN,NaN,NaN,2021-10-23,2020,g,94 min,"crime, drama, thriller","mark, a low end south london hitman recently r...",110,0,as2
2,s3,movie,the marksman,NaN,NaN,NaN,2021-10-23,2021,pg-13,108 min,"action, thriller",a hardened arizona rancher tries to protect an...,74,0,as3
3,s4,movie,gaia,NaN,NaN,NaN,2021-10-22,2021,r,97 min,horror,a forest ranger and two survivalists with a cu...,69,0,as4
4,s5,movie,settlers,NaN,NaN,NaN,2021-10-22,2021,g,104 min,"science fiction, thriller",mankind's earliest settlers on the martian fro...,45,0,as5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3068,s3069,tv show,star trek: the original series,NaN,NaN,united states,NaT,1966,tv-pg,3 seasons,"action, adventure, classics",the 23rd century adventures of captain james t...,56,0,as3069
3069,s3070,tv show,star trek: voyager,NaN,NaN,united states,NaT,1997,tv-pg,7 seasons,"action, adventure, science fiction",catapulted into the distant sector of the gala...,178,0,as3070
3070,s3071,tv show,the fades,NaN,NaN,united kingdom,NaT,2011,tv-14,1 season,"horror, international, science fiction",seventeen-year-old paul is haunted by apocalyp...,0,1,as3071
3071,s3072,tv show,the twilight zone,NaN,NaN,united states,NaT,1959,tv-pg,5 seasons,"classics, science fiction, thriller",rod serling's seminal anthology series focused...,77,0,as3072
3072,s3073,tv show,tokyo magnitude 8.0,NaN,NaN,japan,NaT,2009,tv-14,1 season,"anime, drama, international",the devastation is unleashed in the span of se...,80,0,as3073

In [82]:
#netflix
#creaar ID
netflix['ID']= ['a'] + netflix['show_id']
#remplazar los valores los nulos en raiting por G:
netflix['rating'] = netflix ['rating'].replace(np.nan, 'g')
#formato de fechas 
#fechas marcarcan error, necesitamos quitar los espacios innecesarios
netflix['date_added'] =netflix['date_added']. str.strip()
netflix['date_added'] = pd.to_datetime(netflix['date_added'], format= '%B %d, %Y')
#Modificar los campos de texto para que esten en minusculas
netflix['type'] = netflix['type'].str.lower()
netflix['title'] = netflix['title'].str.lower()
netflix['director'] = netflix['director'].str.lower()
netflix['country'] = netflix['country'].str.lower()
netflix['rating'] = netflix['rating'].str.lower()
netflix['duration'] = netflix['duration'].str.lower()
netflix['listed_in'] = netflix['listed_in'].str.lower()
netflix['description'] = netflix['description'].str.lower()

In [83]:
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons,ID
0,s1,movie,dick johnson is dead,kirsten johnson,NaN,united states,2021-09-25,2020,pg-13,90 min,documentaries,"as her father nears the end of his life, filmm...",113,0,as1
1,s2,tv show,blood & water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",south africa,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, tv dramas, tv mysteries","after crossing paths at a party, a cape town t...",110,0,as2
2,s3,tv show,ganglands,julien leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,tv-ma,1 season,"crime tv shows, international tv shows, tv act...",to protect his family from a powerful drug lor...,74,0,as3
3,s4,tv show,jailbirds new orleans,NaN,NaN,NaN,2021-09-24,2021,tv-ma,1 season,"docuseries, reality tv","feuds, flirtations and toilet talk go down amo...",69,0,as4
4,s5,tv show,kota factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",india,2021-09-24,2021,tv-ma,2 seasons,"international tv shows, romantic tv shows, tv ...",in a city of coaching centers known to train i...,45,0,as5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,movie,zodiac,david fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",united states,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",116,0,as8803
8803,s8804,tv show,zombie dumb,NaN,NaN,NaN,2019-07-01,2018,tv-y7,2 seasons,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",0,4,as8804
8804,s8805,movie,zombieland,ruben fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",united states,2019-11-01,2009,r,88 min,"comedies, horror movies",looking to survive in a world taken over by zo...,120,0,as8805
8805,s8806,movie,zoom,peter hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",united states,2020-01-11,2006,pg,88 min,"children & family movies, comedies","dragged from civilian life, a former superhero...",100,0,as8806
8806,s8807,movie,zubaan,mozez singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",india,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,103,0,as8807

In [84]:
df_conjunto = pd. concat([amazon, disneyplus, hulu, netflix])

In [97]:
#dividir la columna 'duration' en durationt int y duration_type
df_conjunto[['duration_int', 'duration_type']] = df_conjunto['duration'].str.extract('(\d+)\s*(\w+)')

In [100]:
#comprobamos que se hayan realizado los cambios 
df_conjunto

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,min,seasons,ID,duration_int,duration_type
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,113,0,as1,113,min
1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,110,0,as2,110,min
2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,74,0,as3,74,min
3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",69,0,as4,69,min
4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,45,0,as5,45,min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,movie,zodiac,david fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",united states,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",116,0,as8803,158,min
8803,s8804,tv show,zombie dumb,NaN,NaN,NaN,2019-07-01,2018,tv-y7,2 seasons,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",0,4,as8804,2,seasons
8804,s8805,movie,zombieland,ruben fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",united states,2019-11-01,2009,r,88 min,"comedies, horror movies",looking to survive in a world taken over by zo...,120,0,as8805,88,min
8805,s8806,movie,zoom,peter hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",united states,2020-01-11,2006,pg,88 min,"children & family movies, comedies","dragged from civilian life, a former superhero...",100,0,as8806,88,min
8806,s8807,movie,zubaan,mozez singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",india,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,103,0,as8807,111,min

In [102]:
#transformar el dato de la columna "duration" a entero
df_conjunto['duration_int'] = df_conjunto['duration_int'].astype('Int64')

In [104]:
#revisamos los cambios
print(df_conjunto['duration_int'].dtype)

Int64

In [105]:
#revisamos el tipo de datos en las columnas
print(df_conjunto.dtypes)

show_id                  object
type                     object
title                    object
director                 object
cast                     object
country                  object
date_added       datetime64[ns]
release_year              int64
rating                   object
duration                 object
listed_in                object
description              object
min                      object
seasons                  object
ID                       object
duration_int              Int64
duration_type            object
dtype: object

In [106]:
#por ultimo exportamos el archivo a un csv nuevo:
df_conjunto.to_csv('pi_completo.csv', index=False)